AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating DynamoDB Table for serverless-feedback-system"

Parameters:
  FeedbackTableName:
    Type: String
    Description: Name of Table
    Default: "FeedbackTable"
  RatingTableName:
    Type: String
    Description: Name of Table
    Default: "FeedbackRatingStatsTable"

Resources:
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FeedbackTableName
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: serverless-feedback-system
        - Key: Environment
          Value: Dev


  RatingStatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref RatingTableName
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: serverless-feedback-system
        - Key: Environment
          Value: Dev

Outputs:
  FeedbackTableStreamArn:
    Value: !GetAtt FeedbackTable.StreamArn
    Export:
      Name: FeedbackTable-StreamArn